theme: jekyll-theme-cayman

<div id="gitalk-container"></div>

var gitalk = new Gitalk({
  clientID: '6ffe2db84139272698af',
  clientSecret: 'f0ca780aa3b773a31ab646f1f53a81d16d83da2f',
  repo: 'Maktiny.github.io',
  owner: 'Maktiny',
  admin: ['Maktiny'],
  id: location.pathname,      // Ensure uniqueness and length less than 50
  distractionFreeMode: true  // Facebook-like distraction free mode
})

